- name: Configuring Devops-Forge-EC2 instance
  hosts: webservers
  become: true

  tasks:
    - name: Updating apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installing nginx
      apt:
        name: nginx
        state: present

    - name: Starting nginx and keeping it running
      service:
        name: nginx
        state: started	# keeps nginx running
        enabled: yes	# starts and runs nginx upon reboot
